- name: Ensure old container is stopped and removed
  community.docker.docker_container:
    name: "my-app-container"
    state: absent

- name: Run the Docker container
  community.docker.docker_container:
    name: "my-app-container"
    image: "romanbordei4yk/jenkins-pipeline-lab-bordeichuk:latest"
    state: started
    restart_policy: always
    published_ports:
      - "8180:8080"
